<a href="https://colab.research.google.com/github/mamatqobulovsardor/mamatqobulovsardor/blob/main/google_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
! wget https://raw.githubusercontent.com/dataprofessor/data/master/delaney_solubility_with_descriptors.csv

--2024-11-10 17:20:05--  https://raw.githubusercontent.com/dataprofessor/data/master/delaney_solubility_with_descriptors.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 57370 (56K) [text/plain]
Saving to: ‘delaney_solubility_with_descriptors.csv’

delaney_solubility_ 100%[===================>]  56.03K  --.-KB/s    in 0.005s

2024-11-10 17:20:05 (11.4 MB/s) - ‘delaney_solubility_with_descriptors.csv’ saved [57370/57370]

In [3]:
df = pd.read_csv('delaney_solubility_with_descriptors.csv')
df

      MolLogP    MolWt  NumRotatableBonds  AromaticProportion   logS
0     2.59540  167.850                0.0            0.000000 -2.180
1     2.37650  133.405                0.0            0.000000 -2.000
2     2.59380  167.850                1.0            0.000000 -1.740
3     2.02890  133.405                1.0            0.000000 -1.480
4     2.91890  187.375                1.0            0.000000 -3.040
...       ...      ...                ...                 ...    ...
1139  1.98820  287.343                8.0            0.000000  1.144
1140  3.42130  286.114                2.0            0.333333 -4.925
1141  3.60960  308.333                4.0            0.695652 -3.893
1142  2.56214  354.815                3.0            0.521739 -3.790
1143  2.02164  179.219                1.0            0.461538 -2.581

[1144 rows x 5 columns]

Bitta ustunni tanlash

In [4]:
df.MolLogP

0       2.59540
1       2.37650
2       2.59380
3       2.02890
4       2.91890
         ...
1139    1.98820
1140    3.42130
1141    3.60960
1142    2.56214
1143    2.02164
Name: MolLogP, Length: 1144, dtype: float64

In [5]:
df['MolLogP']

0       2.59540
1       2.37650
2       2.59380
3       2.02890
4       2.91890
         ...
1139    1.98820
1140    3.42130
1141    3.60960
1142    2.56214
1143    2.02164
Name: MolLogP, Length: 1144, dtype: float64

Ikki yoki undan ortiq ustunlarni tanlash

In [6]:
df[['MolLogP', 'NumRotatableBonds']]

      MolLogP  NumRotatableBonds
0     2.59540                0.0
1     2.37650                0.0
2     2.59380                1.0
3     2.02890                1.0
4     2.91890                1.0
...       ...                ...
1139  1.98820                8.0
1140  3.42130                2.0
1141  3.60960                4.0
1142  2.56214                3.0
1143  2.02164                1.0

[1144 rows x 2 columns]

In [7]:
df.iloc[:,[0,2]]

      MolLogP  NumRotatableBonds
0     2.59540                0.0
1     2.37650                0.0
2     2.59380                1.0
3     2.02890                1.0
4     2.91890                1.0
...       ...                ...
1139  1.98820                8.0
1140  3.42130                2.0
1141  3.60960                4.0
1142  2.56214                3.0
1143  2.02164                1.0

[1144 rows x 2 columns]

In [8]:
selection = ['MolLogP','NumRotatableBonds', 'logS']
df[selection]

      MolLogP  NumRotatableBonds   logS
0     2.59540                0.0 -2.180
1     2.37650                0.0 -2.000
2     2.59380                1.0 -1.740
3     2.02890                1.0 -1.480
4     2.91890                1.0 -3.040
...       ...                ...    ...
1139  1.98820                8.0  1.144
1140  3.42130                2.0 -4.925
1141  3.60960                4.0 -3.893
1142  2.56214                3.0 -3.790
1143  2.02164                1.0 -2.581

[1144 rows x 3 columns]


Pandas DataFrame uslubini yaratish

In [9]:
import numpy as np

In [10]:
! wget https://raw.githubusercontent.com/dataprofessor/data/master/nba-player-stats-2019.csv

--2024-11-10 17:20:06--  https://raw.githubusercontent.com/dataprofessor/data/master/nba-player-stats-2019.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 90308 (88K) [text/plain]
Saving to: ‘nba-player-stats-2019.csv’

nba-player-stats-20 100%[===================>]  88.19K  --.-KB/s    in 0.007s

2024-11-10 17:20:06 (11.5 MB/s) - ‘nba-player-stats-2019.csv’ saved [90308/90308]

In [11]:
data = pd.read_csv('nba-player-stats-2019.csv')
selection = ['Player','Pos','Age','Tm','G','3P%','2P%','FT%','AST','STL','BLK','PTS']

In [14]:
data = data[selection]

Style pandas table with CSS

In [21]:
data.head(20).style.set_table_styles(
    [
        {'selector': 'th',
         'props': [('background-color', '#7CAE00'),
                   ('color', 'white'),
                   ('font-family', 'verdana')]},

        {'selector': 'td',
         'props': [('font-family', 'verdana')]},

        {'selector': 'tr:nth-of-type(odd)',
         'props': [('background-color', '#DCDCDC')]},

        {'selector': 'tr:nth-of-type(even)',
         'props': [('background-color', 'white')]},
    ]
).hide(axis="index")

Adding yellow highlight upon hover

In [23]:
data.head(20).style.set_table_styles(
[{'selector': 'th',
  'props': [('background', '#7CAE00'),
            ('color', 'white'),
            ('font-family', 'verdana')]},

 {'selector': 'td',
  'props': [('font-family', 'verdana')]},

 {'selector': 'tr:nth-of-type(odd)',
  'props': [('background', '#DCDCDC')]},

 {'selector': 'tr:nth-of-type(even)',
  'props': [('background', 'white')]},

 {'selector': 'tr:hover',
  'props': [('background-color', 'yellow')]}

]
).hide(axis="index")

Conditional coloring

In [24]:
def color_red(val):
  if val > 20:
    color = 'green'
  elif val > 5:
    color = 'red'
  else:
    color = 'black'
  return 'color: %s' % color

data[['PTS']].head(20).style.applymap(color_red)

<ipython-input-24-e6d504de8634>:10: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  data[['PTS']].head(20).style.applymap(color_red)

In [25]:
data[['Player','Pos','Tm']].head(20)

                    Player Pos   Tm
0             Álex Abrines  SG  OKC
1               Quincy Acy  PF  PHO
2             Jaylen Adams  PG  ATL
3             Steven Adams   C  OKC
4              Bam Adebayo   C  MIA
5                Deng Adel  SF  CLE
6   DeVaughn Akoon-Purcell  SG  DEN
7        LaMarcus Aldridge   C  SAS
8             Rawle Alkins  SG  CHI
9            Grayson Allen  SG  UTA
10           Jarrett Allen   C  BRK
11            Kadeem Allen  SG  NYK
12         Al-Farouq Aminu  PF  POR
13         Justin Anderson  SF  ATL
14           Kyle Anderson  SF  MEM
15           Ryan Anderson  PF  TOT
16           Ryan Anderson  PF  PHO
17           Ryan Anderson  PF  MIA
18            Ike Anigbogu   C  IND
19   Giannis Antetokounmpo  PF  MIL